### ISSUE TITLE
editing FloorPlot boxes

### ISSUE THREAD

**Issue by cchall** [xsuite/xplt#17]
I'm trying to use the FloorPlot function on a simple beamline imported in from MAD-X. Plotting with mostly default options seems to work well:
```
xplt.FloorPlot(
    sv, line, 
    figsize=(18, 7),
    labels=table_multipoles.name
)
```
![image](https://github.com/user-attachments/assets/b88ab0d2-a055-4bc8-81f2-e1cdc9c3cb38)

However, when I go to edit the color of my kickers (imported as multipoles) something strange seems to happen. I'm guessing this is connected with `".*: "True"` to get the other elements to plot in their default configuration?

``` 
    xplt.FloorPlot(
        sv, line, 
        figsize=(18, 7),
        boxes={
            "vs.": dict(color="green"),
            "s.": dict(color="green"),
            ".*": True
        },
        labels=table_multipoles.name
    )
```
![image](https://github.com/user-attachments/assets/2bb97cc9-1e67-48b1-be1d-21e81f092d2d)

**Comment by eltos** [comment]
Yes, since `.*` matches everything, you overwrite the default behaviour and ask it to show all elements explicitly.

What elements are the ones you don't want to show up? Can you provide the MADX file and minimal code to reproduce?

If it's drift spaces then it's a bug because these should never be rendered. In this case we need a reproducible example to debug.

If it's some other elements then it's intended behaviour. In this case you can either change the regex to match only the elements you actually want to see, or use the `ignore` parameter to exclude certain elements again. But we could think about having a `default_boxes=True/False` parameter to keep the default boxes _in addition to_ custom ones for convenience (instead of forcing the user to manually replicate the default by providing an appropriate regex).

**Comment by eltos** [comment]
But in any case please provide a reproducible minimal example.

**Comment by cchall** [comment]
It looks like this was caused by the drift spaces being rendered from including `.*`. I'm not sure from your statement if this is actually a bug or is expected when you ask for every element to be shown.
In either case the addition of `default_boxes` seems to make it much easier to create the figure I intended. Thanks for your help!

As a side issue it looks like the coloring for Bend elements may have been  broken in the recent commits. They now appear to default to the same color as Quads.

```
import xtrack as xt
import xpart as xp
import xplt
xplt.apply_style()

ele_line = {
    'drift_0': xt.Drift(length=0.5),
    'qf_0': xt.Quadrupole(length=0.25, k1=1.0),
    'drift_1': xt.Drift(length=0.5),
    'qd_0': xt.Quadrupole(length=0.25, k1=-1.0),

    'drift_2': xt.Drift(length=0.5),
    'bend_0': xt.Bend(length=0.175, h=0.686, edge_entry_angle=0, edge_exit_angle=0.06),
    'drift_3': xt.Drift(length=0.5),
    'bend_1': xt.Bend(length=0.175, h=-0.686, edge_entry_angle=-0.06, edge_exit_angle=0.0),
}

beam_line = xt.Line(
    elements=[ele for ele in ele_line.values()],
    element_names=[name for name in ele_line.keys()]
              )

beam_line.particle_ref = xp.Particles()
beam_line.build_tracker()
table = beam_line.get_table()
```
```
plot = xplt.FloorPlot(line=beam_line, labels=table.rows[table.element_type == 'Bend'].name)
plot.legend()
```
![image](https://github.com/user-attachments/assets/397c17eb-fdf0-468c-be63-d8fcd12a4ddf)
```
plot = xplt.FloorPlot(line=beam_line, boxes={'.*': True})
plot.legend()
```
![image](https://github.com/user-attachments/assets/8c44d28a-6a1c-4e2f-8ead-90e6a5140bf4)
