### ISSUE TITLE
FloorPlot Repeated Elements

### ISSUE THREAD

**Issue by Binabek** [xsuite/xplt#31]
The FloorPlot routine no longer handles repeated elements. It looks like xsuite has changed to handling repeated elements by appending the names with an identifying index ::## . Somewhere in xplt this doesn't line up with the list of names. Only fails if the xsute line object is included in FloorPlot call. A short example below produces the error:

import xtrack as xt
import xplt

xline_elem = {"obm": xt.Drift(length=0.2205)}
xline_list = ["obm","obm"]

doubledrift = xt.Line(
    elements = xline_elem,
    element_names= xline_list
)

sv_hdb = doubledrift.survey()

xplt.FloorPlot(sv_hdb.rows[:],doubledrift)

**Stack Trace**
-------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[6], line 3
      1 sv_hdb = doubledrift.survey()
----> 3 xplt.FloorPlot(sv_hdb.rows[:],doubledrift)

File [~/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xplt/line.py:316](http://localhost:8888/lab/tree/Downloads/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xplt/line.py#line=315), in FloorPlot.__init__(self, survey, line, projection, boxes, labels, ignore, element_width, **kwargs)
    314     survey = line.survey()
    315 if survey is not None:
--> 316     self.update(survey, line)

File [~/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xplt/line.py:390](http://localhost:8888/lab/tree/Downloads/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xplt/line.py#line=389), in FloorPlot.update(self, survey, line, autoscale)
    388     if name == "_end_point":
    389         continue
--> 390     if line[name].__class__.__name__ == "Replica":
    391         name = line[name].resolve(line, get_name=True)
    393 # ignored elements

File [~/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xtrack/line.py:4061](http://localhost:8888/lab/tree/Downloads/Software/miniforge3/envs/xsuite/lib/python3.13/site-packages/xtrack/line.py#line=4060), in Line.__getitem__(self, key)
   4059     return self.lines[key]
   4060 else:
-> 4061     raise KeyError(f'Name {key} not found')

KeyError: 'Name obm::0 not found'

**Environment**
- OS
Ubuntu 24.04.1 LTS
- python and library versions
python==3.13.0
xcoll==0.5.11
xdeps==0.8.1
xfields==0.21.3
xobjects==0.4.5
xpart==0.19.3
xplt==0.10.1
xsuite==0.19.5
xtrack==0.70.3

**Comment by Binabek** [comment]
The `line.replace_all_repeated_elements()` call worked at treat for my purposes, thanks!

**Comment by giadarol** [comment]
Hello, my proposal would be to add to the survey table all the columns that are needed (including `env_name`). Alternative one can also manipulate the string getting `el_name=name.split('::')[0]`

Note that the FloorPlot can be obtained by calling `line.survey().plot()`. I believe I have tested this way with repeated elements and it worked fine.

**Comment by eltos** [comment]
> Hello, my proposal would be to add to the survey table all the columns that are needed (including `env_name`). Alternatively one can also manipulate the string getting `el_name=name.split('::')[0]`

@giadarol That would work, but would mean that code in xplt (and any other code users will write to work with survey results) relies on an implementation detail from xtrack. If in the future you decide to change this again (e.g. make the renaming optional or change the separator), every code using that will break again. IMHO it's better to keep that in one place (namely xtrack), then you can simply add a test there and ensure that the "public" API will not change.

In any case, is there a benefit of raising an exception for `line["obm::0"]` rather than just returning `line["obm"]` like proposed in https://github.com/xsuite/xtrack/pull/561?



> Note that the FloorPlot can be obtained by calling `line.survey().plot()`. I believe I have tested this way with repeated elements and it worked fine.

Indeed, that's because in [that wrapper function](https://github.com/xsuite/xtrack/blob/0ac22aeefb72b69b9c56ff1b47185ccc786f78b8/xtrack/survey.py#L177C9-L177C86), there is a hack overwriting the names in survey again:
```python
out_sv_table.name = np.array([nn.split('::')[0] for nn in out_sv_table.name])
```
